### PR TITLE
feat: :sparkles: class list

### PR DESCRIPTION
**Pull request by AvaN0x**
Closes #

## 🎯 Changes

What changes are made in this PR? Is it a feature or a bug fix?

## ✅ Checklist

- [ ] I have followed the steps listed in the [Contributing guide](https://github.com/pedakihq/pedaki/blob/main/CONTRIBUTING.md).
- [ ] I have added or updated the tests related to the changes made.

### CODE REVIEW

**Comment by Vahor** [comment]
Moyen de faire moins de copier collé ? Il y a 30% de code en double là

**Comment by AvaN0x** [comment]
> Moyen de faire moins de copier collé ? Il y a 26% de code en double là

Yes, je voulais surtout voir les code check de github actions

**Comment by Vahor** [comment]
Quand on fait un sort sur les professeurs ça ne marche plus
```
@pedaki/community:dev: Unknown argument `name`. Available options are marked with ?.
@pedaki/community:dev:
@pedaki/community:dev: Invalid `prisma.class.findMany()` invocation:
@pedaki/community:dev:
@pedaki/community:dev: {
@pedaki/community:dev:   select: {
@pedaki/community:dev:     id: undefined,
@pedaki/community:dev:     name: true,
@pedaki/community:dev:     description: true,
@pedaki/community:dev:     academicYear: {
@pedaki/community:dev:       select: {
@pedaki/community:dev:         id: true,
@pedaki/community:dev:         name: undefined,
@pedaki/community:dev:         startDate: undefined,
@pedaki/community:dev:         endDate: undefined
@pedaki/community:dev:       }
@pedaki/community:dev:     },
@pedaki/community:dev:     level: {
@pedaki/community:dev:       select: {
@pedaki/community:dev:         id: true,
@pedaki/community:dev:         name: undefined,
@pedaki/community:dev:         description: undefined
@pedaki/community:dev:       }
@pedaki/community:dev:     },
@pedaki/community:dev:     teachers: {
@pedaki/community:dev:       select: {
@pedaki/community:dev:         id: true,
@pedaki/community:dev:         name: undefined
@pedaki/community:dev:       }
@pedaki/community:dev:     },
@pedaki/community:dev:     mainTeacher: {
@pedaki/community:dev:       select: {
@pedaki/community:dev:         id: true,
@pedaki/community:dev:         name: undefined
@pedaki/community:dev:       }
@pedaki/community:dev:     },
@pedaki/community:dev:     branches: undefined
@pedaki/community:dev:   },
@pedaki/community:dev:   where: {},
@pedaki/community:dev:   orderBy: {
@pedaki/community:dev:     teachers: {
@pedaki/community:dev:       name: "desc",
@pedaki/community:dev:       ~~~~
@pedaki/community:dev: ?     _count?: SortOrder
@pedaki/community:dev:     }
@pedaki/community:dev:   },
@pedaki/community:dev:   skip: 0,
@pedaki/community:dev:   take: 25
@pedaki/community:dev: }
@pedaki/community:dev:
@pedaki/community:dev: Unknown argument `name`. Available options are marked with ?.
```

**Review by Vahor — CHANGES_REQUESTED** [review]
Quand on fait un sort sur les professeurs ou branches ça ne marche plus
```
@pedaki/community:dev: Unknown argument `name`. Available options are marked with ?.
@pedaki/community:dev:
@pedaki/community:dev: Invalid `prisma.class.findMany()` invocation:
@pedaki/community:dev:
@pedaki/community:dev: {
@pedaki/community:dev:   select: {
@pedaki/community:dev:     id: undefined,
@pedaki/community:dev:     name: true,
@pedaki/community:dev:     description: true,
@pedaki/community:dev:     academicYear: {
@pedaki/community:dev:       select: {
@pedaki/community:dev:         id: true,
@pedaki/community:dev:         name: undefined,
@pedaki/community:dev:         startDate: undefined,
@pedaki/community:dev:         endDate: undefined
@pedaki/community:dev:       }
@pedaki/community:dev:     },
@pedaki/community:dev:     level: {
@pedaki/community:dev:       select: {
@pedaki/community:dev:         id: true,
@pedaki/community:dev:         name: undefined,
@pedaki/community:dev:         description: undefined
@pedaki/community:dev:       }
@pedaki/community:dev:     },
@pedaki/community:dev:     teachers: {
@pedaki/community:dev:       select: {
@pedaki/community:dev:         id: true,
@pedaki/community:dev:         name: undefined
@pedaki/community:dev:       }
@pedaki/community:dev:     },
@pedaki/community:dev:     mainTeacher: {
@pedaki/community:dev:       select: {
@pedaki/community:dev:         id: true,
@pedaki/community:dev:         name: undefined
@pedaki/community:dev:       }
@pedaki/community:dev:     },
@pedaki/community:dev:     branches: undefined
@pedaki/community:dev:   },
@pedaki/community:dev:   where: {},
@pedaki/community:dev:   orderBy: {
@pedaki/community:dev:     teachers: {
@pedaki/community:dev:       name: "desc",
@pedaki/community:dev:       ~~~~
@pedaki/community:dev: ?     _count?: SortOrder
@pedaki/community:dev:     }
@pedaki/community:dev:   },
@pedaki/community:dev:   skip: 0,
@pedaki/community:dev:   take: 25
@pedaki/community:dev: }
@pedaki/community:dev:
@pedaki/community:dev: Unknown argument `name`. Available options are marked with ?.
```

**Comment by AvaN0x** [comment]
> Quand on fait un sort sur les professeurs ou branches ça ne marche plus
> 
> ```
> @pedaki/community:dev: Unknown argument `name`. Available options are marked with ?.
> @pedaki/community:dev:
> @pedaki/community:dev: Invalid `prisma.class.findMany()` invocation:
> @pedaki/community:dev:
> @pedaki/community:dev: {
> @pedaki/community:dev:   select: {
> @pedaki/community:dev:     id: undefined,
> @pedaki/community:dev:     name: true,
> @pedaki/community:dev:     description: true,
> @pedaki/community:dev:     academicYear: {
> @pedaki/community:dev:       select: {
> @pedaki/community:dev:         id: true,
> @pedaki/community:dev:         name: undefined,
> @pedaki/community:dev:         startDate: undefined,
> @pedaki/community:dev:         endDate: undefined
> @pedaki/community:dev:       }
> @pedaki/community:dev:     },
> @pedaki/community:dev:     level: {
> @pedaki/community:dev:       select: {
> @pedaki/community:dev:         id: true,
> @pedaki/community:dev:         name: undefined,
> @pedaki/community:dev:         description: undefined
> @pedaki/community:dev:       }
> @pedaki/community:dev:     },
> @pedaki/community:dev:     teachers: {
> @pedaki/community:dev:       select: {
> @pedaki/community:dev:         id: true,
> @pedaki/community:dev:         name: undefined
> @pedaki/community:dev:       }
> @pedaki/community:dev:     },
> @pedaki/community:dev:     mainTeacher: {
> @pedaki/community:dev:       select: {
> @pedaki/community:dev:         id: true,
> @pedaki/community:dev:         name: undefined
> @pedaki/community:dev:       }
> @pedaki/community:dev:     },
> @pedaki/community:dev:     branches: undefined
> @pedaki/community:dev:   },
> @pedaki/community:dev:   where: {},
> @pedaki/community:dev:   orderBy: {
> @pedaki/community:dev:     teachers: {
> @pedaki/community:dev:       name: "desc",
> @pedaki/community:dev:       ~~~~
> @pedaki/community:dev: ?     _count?: SortOrder
> @pedaki/community:dev:     }
> @pedaki/community:dev:   },
> @pedaki/community:dev:   skip: 0,
> @pedaki/community:dev:   take: 25
> @pedaki/community:dev: }
> @pedaki/community:dev:
> @pedaki/community:dev: Unknown argument `name`. Available options are marked with ?.
> ```

Corrigé dans les derniers commits

**Review by Vahor — APPROVED** [review]

**Pull request merged**
